export const testResponse = {
  message: "Success",
  status: 201,
  text: "\n\n \nALEX \nBENNY \nCONTACT \nEmail: \nalexbennyincorps@gmail.com \n \nPhone: \n+91 8287615871 \n \nAddress: \nRZ-61, South Extension Part-1, \nUttam Nagar, New Delhi-110059 \nSOFT SKILLS \n• Problem Solving   \n• Time Management \n• Team Player \n• Curious Learner \nLANGUAGES KNOWN \n• English   \n• Hindi \nHOBBIES \n• Design \n• Basketball \n• Photography \nEDUCATION \nCOURSE/CLASS INSTITUTION YEAR OF \nPASSING \nPERFORMANCE \nB.Sc. Physical \nScience \nSt. Stephen’s College, \nDelhi University \n2022 9 CGPA \nAISSCE  \n(Class XII) \nSt. Francis De Sales \nSchool, Delhi \n2019 91.4 % \nAISSE  \n(Class X) \nSt. Francis De Sales \nSchool, Delhi \n2017 9.8 CGPA \nPOSITIONS OF RESPONSIBILITY \nCOUNCIL MEMBER \nPhotographic Society, St. Stephen’s College, 2020 - Present \n• was responsible for organizing photos, designing and \ndelivering the official 2021 College Calendar, which sold over \n400 copies. \n• Was in charge of contacting judges and organizing \nPhotoshop Battles, an All-India level competition for the \nsociety's mini-fest, Breaking Frames. \n• was in charge of contacting judges and arranging Main \nExhibition and Photo Manipulation All-India level contests \nfor the society's annual fest, Frames 2021, which attracted \nover 100 participants. \nINTERNSHIPS \nGRAPHIC DESIGN INTERN \nEveroutdoor India, January 2021 – February 2021 \n• was in charge of designing visuals and designs for social \nmedia. \n \nTECHNICAL SKILLS \n• C++ • Python \n• SQL • Adobe Photoshop \n• Adobe Illustrator • Microsoft Office \nEXTRA CURRICULAR ACTIVITIES \n• 3\nrd\n position in the Basketball Zonal School Competition \nZONE–18 - (2018-19) \n• Donated Blood at Blood Donation Camp - (2019) \nOTHER ACHIEVEMENTS \n• Secured   AIR 98097(/9LAKH+   students)   in Joint   Entrance \nExamination Mains 2019 ",
  goodPointers:
    "\n\n## What's good\n\n**Strong Profile:**\n\n- Clear and concise summary of the candidate's name, contact information, and key skills.\n- Strong soft skills including problem-solving, time management, and teamwork.\n- Languages known including English and Hindi.\n- Hobbies showcasing creativity and athleticism.\n\n**Well-Structured Education:**\n\n- Clear and concise listing of educational qualifications.\n- Excellent academic performance with high CGPA and percentage.\n- Recognition of achievements through AISSE and POSITIONS OF RESPONSIBILITY.\n\n**Impressive Achievements:**\n\n- Secured AIR 98097(/9LAKH+ students) in Joint Entrance Examination Mains 2019.\n- Achievements in extracurricular activities including basketball and blood donation.\n- Active participation in the Photographic Society and contribution to college events.\n\n**Strong Technical Skills:**\n\n- Proficiency in C++, Python, SQL, Adobe Photoshop, and Illustrator.\n- Ability to manage multiple software and tools effectively.\n- Demonstrated design skills through internship and college projects.\n\n**Overall:**\n\nThis resume showcases the candidate's strong profile, excellent education, impressive achievements, and impressive technical skills. The text is well-structured, concise, and easy to read. The candidate's accomplishments are highlighted effectively, and the resume provides a clear overview of their qualifications and potential.",
  badPointers:
    "\n\n## Shortcomings\n\n**1. Lack of Objective Information:**\n\n**Issue:** The resume lacks specific objective information such as the candidate's career goals, personal interests, and aspirations.\n\n**Solution:** Include a brief objective statement outlining the candidate's goals and objectives for the position.\n\n**2. Unclear Action Verbs:**\n\n**Issue:** Some action verbs used in the resume are vague and could be improved. For example, \"was responsible for organizing photos\" could be rewritten as \"was responsible for meticulously organizing photos.\"\n\n**Solution:** Use strong, specific action verbs that clearly convey the candidate's accomplishments.\n\n**3. Incomplete Education Information:**\n\n**Issue:** The candidate's education information is incomplete as it only includes their college and school education. They have not included any professional certifications or training programs.\n\n**Solution:** Include all relevant education and training programs, along with the dates and institutions attended.\n\n**4. Lack of Professional Experience:**\n\n**Issue:** The resume does not include any professional experience or work history. The candidate has only listed their extracurricular activities and internships.\n\n**Solution:** Include any professional experience, even if it is part-time or volunteer work.\n\n**5. Unclear Reference to Skills:**\n\n**Issue:** While the candidate lists their soft and technical skills, there is no clear connection between those skills and their experience or accomplishments.\n\n**Solution:** Connect the listed skills to the candidate's experience and accomplishments by highlighting how they use those skills in their roles.",
  scoreResume: "89",
  jobs: [
    '"Graphic Designer"',
    '"Software Developer"',
    '"Data Analyst"',
    '"Web Designer"',
    '"Photographer"',
  ],
};
